import { Inter } from "next/font/google";
import "./globals.css";
import headerStyles from "./test-folder/header.module.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <header className={headerStyles.header} />
      <body className={inter.className}>{children}</body>
    </html>
  );
}
